apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      containers:
        - name: application-container
          image: 570629616813.dkr.ecr.us-east-1.amazonaws.com/app-image-clo835-final-project:latest
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: username
            - name: DBHOST
              value: "mysql.final.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: bucket
            - name: BGIMG
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: bgimg
            - name: GRPNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: grpname
          resources:
            requests:
              cpu: 15m
            limits:
              cpu: 50m
          ports:
            - containerPort: 81
      imagePullSecrets:
        - name: regcred